server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb
    username: quiz_user
    password: quiz_pass
    driver-class-name: org.postgresql.Driver
  application:
    name: Quereria

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml